<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HXD4UK_HSZF_20242501.Application\HXD4UK_HSZF_20242501.Application.csproj" />
    <ProjectReference Include="..\HXD4UK_HSZF_20242501.Model\HXD4UK_HSZF_20242501.Model.csproj" />
    <ProjectReference Include="..\HXD4UK_HSZF_20242501.Persistence.MsSql\HXD4UK_HSZF_20242501.Persistence.MsSql.csproj" />
  </ItemGroup>

</Project>
